version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":dependabot: devcontainers"
      include: "scope"
    cooldown:
      default-days: 7
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "numpy"
        versions: [ ">=2.0.0" ]
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    groups:
      support-dependencies:
        patterns:
          - ".github/workflows/*"
