version: "3"

services:
  frontend:
    image: ${IMAGE_NAME}:${IMAGE_TAG-latest}
    stdin_open: true
    tty: true
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes: [
      ./controlpanel:/home/controlpanel/controlpanel,
      ./tests:/home/controlpanel/tests
    ]
  migration:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
    command: "python manage.py migrate"
  worker:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    stdin_open: true
    tty: true
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
    command: ["python", "manage.py", "runworker", "background_tasks"]
