version: "3"

services:
  frontend:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    build:
      context: .
      network: ${NETWORK:-default}
      dockerfile: Dockerfile

    stdin_open: true
    tty: true
    command: ["./startup_dev_frontend.sh"]
    volumes: [
      ./controlpanel:/home/controlpanel/controlpanel,
      ./tests:/home/controlpanel/tests
    ]
  migration:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    build:
      context: .
      network: ${NETWORK:-default}
      dockerfile: Dockerfile
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
    command: ["./startup_dev_migration.sh"]
  worker:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    build:
      context: .
      network: ${NETWORK:-default}
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
    command: ["./startup_dev_worker.sh"]
