version: "3"

services:
  frontend:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
    environment:
      OIDC_OP_AUTHORIZATION_ENDPOINT: ${OIDC_OP_AUTHORIZATION_ENDPOINT}
      OIDC_OP_JWKS_ENDPOINT: ${OIDC_OP_JWKS_ENDPOINT}
      OIDC_OP_TOKEN_ENDPOINT: ${OIDC_OP_TOKEN_ENDPOINT}
      OIDC_OP_USER_ENDPOINT: ${OIDC_OP_USER_ENDPOINT}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_RP_SIGN_ALGO: "RS256"
      AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
      AWS_DATA_ACCOUNT_ID: ${AWS_DATA_ACCOUNT_ID}
      AWS_COMPUTE_ACCOUNT_ID: ${AWS_COMPUTE_ACCOUNT_ID}
      TOOLS_DOMAIN: tools.dev.mojanalytics.xyz
      RSTUDIO_AUTH_CLIENT_ID: ${RSTUDIO_AUTH_CLIENT_ID}
      RSTUDIO_AUTH_CLIENT_SECRET: ${RSTUDIO_AUTH_CLIENT_SECRET}
      JUPYTER_LAB_AUTH_CLIENT_ID: ${JUPYTER_LAB_AUTH_CLIENT_ID}
      JUPYTER_LAB_AUTH_CLIENT_SECRET: ${JUPYTER_LAB_AUTH_CLIENT_SECRET}
      AIRFLOW_AUTH_CLIENT_ID: ${AIRFLOW_AUTH_CLIENT_ID}
      AIRFLOW_AUTH_CLIENT_SECRET: ${AIRFLOW_AUTH_CLIENT_SECRET}
      AIRFLOW_FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW_SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      IAM_ARN_BASE: ${IAM_ARN_BASE}
      K8S_WORKER_ROLE_NAME: ${K8S_WORKER_ROLE_NAME}
      NFS_HOSTNAME: ${NFS_HOSTNAME}
      LOGS_BUCKET_NAME: ${LOGS_BUCKET_NAME}
      SAML_PROVIDER: ${SAML_PROVIDER}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}

  migration:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
    environment:
      OIDC_OP_AUTHORIZATION_ENDPOINT: ${OIDC_OP_AUTHORIZATION_ENDPOINT}
      OIDC_OP_JWKS_ENDPOINT: ${OIDC_OP_JWKS_ENDPOINT}
      OIDC_OP_TOKEN_ENDPOINT: ${OIDC_OP_TOKEN_ENDPOINT}
      OIDC_OP_USER_ENDPOINT: ${OIDC_OP_USER_ENDPOINT}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_RP_SIGN_ALGO: "RS256"
      AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
      AWS_DATA_ACCOUNT_ID: ${AWS_DATA_ACCOUNT_ID}
      AWS_COMPUTE_ACCOUNT_ID: ${AWS_COMPUTE_ACCOUNT_ID}
      TOOLS_DOMAIN: tools.dev.mojanalytics.xyz
      RSTUDIO_AUTH_CLIENT_ID: ${RSTUDIO_AUTH_CLIENT_ID}
      RSTUDIO_AUTH_CLIENT_SECRET: ${RSTUDIO_AUTH_CLIENT_SECRET}
      JUPYTER_LAB_AUTH_CLIENT_ID: ${JUPYTER_LAB_AUTH_CLIENT_ID}
      JUPYTER_LAB_AUTH_CLIENT_SECRET: ${JUPYTER_LAB_AUTH_CLIENT_SECRET}
      AIRFLOW_AUTH_CLIENT_ID: ${AIRFLOW_AUTH_CLIENT_ID}
      AIRFLOW_AUTH_CLIENT_SECRET: ${AIRFLOW_AUTH_CLIENT_SECRET}
      AIRFLOW_FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW_SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      IAM_ARN_BASE: ${IAM_ARN_BASE}
      K8S_WORKER_ROLE_NAME: ${K8S_WORKER_ROLE_NAME}
      NFS_HOSTNAME: ${NFS_HOSTNAME}
      LOGS_BUCKET_NAME: ${LOGS_BUCKET_NAME}
      SAML_PROVIDER: ${SAML_PROVIDER}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      AWS_DEFAULT_REGION:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}

  worker:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
    environment:
      OIDC_OP_AUTHORIZATION_ENDPOINT: ${OIDC_OP_AUTHORIZATION_ENDPOINT}
      OIDC_OP_JWKS_ENDPOINT: ${OIDC_OP_JWKS_ENDPOINT}
      OIDC_OP_TOKEN_ENDPOINT: ${OIDC_OP_TOKEN_ENDPOINT}
      OIDC_OP_USER_ENDPOINT: ${OIDC_OP_USER_ENDPOINT}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_RP_SIGN_ALGO: "RS256"
      AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
      AWS_DATA_ACCOUNT_ID: ${AWS_DATA_ACCOUNT_ID}
      AWS_COMPUTE_ACCOUNT_ID: ${AWS_COMPUTE_ACCOUNT_ID}
      TOOLS_DOMAIN: tools.dev.mojanalytics.xyz
      RSTUDIO_AUTH_CLIENT_ID: ${RSTUDIO_AUTH_CLIENT_ID}
      RSTUDIO_AUTH_CLIENT_SECRET: ${RSTUDIO_AUTH_CLIENT_SECRET}
      JUPYTER_LAB_AUTH_CLIENT_ID: ${JUPYTER_LAB_AUTH_CLIENT_ID}
      JUPYTER_LAB_AUTH_CLIENT_SECRET: ${JUPYTER_LAB_AUTH_CLIENT_SECRET}
      AIRFLOW_AUTH_CLIENT_ID: ${AIRFLOW_AUTH_CLIENT_ID}
      AIRFLOW_AUTH_CLIENT_SECRET: ${AIRFLOW_AUTH_CLIENT_SECRET}
      AIRFLOW_FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW_SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      IAM_ARN_BASE: ${IAM_ARN_BASE}
      K8S_WORKER_ROLE_NAME: ${K8S_WORKER_ROLE_NAME}
      NFS_HOSTNAME: ${NFS_HOSTNAME}
      LOGS_BUCKET_NAME: ${LOGS_BUCKET_NAME}
      SAML_PROVIDER: ${SAML_PROVIDER}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
