version: "3"

services:
  frontend:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    stdin_open: true
    tty: true
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
  migration:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
    command: "python manage.py migrate"
  worker:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    stdin_open: true
    tty: true
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
    command: ["python", "manage.py", "runworker", "background_tasks"]
