version: "3"

services:
  frontend_eks:
    image: ${REGISTRY}/${REPOSITORY}_eks:${IMAGE_TAG:-latest}
    stdin_open: true
    tty: true
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes: [
      ./controlpanel:/home/controlpanel/controlpanel,
      ./tests:/home/controlpanel/tests,
    ]

  frontend:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    stdin_open: true
    tty: true
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes: [
      ./controlpanel:/home/controlpanel/controlpanel,
      ./tests:/home/controlpanel/tests,
    ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
  migration:
    image: ${REGISTRY}/${REPOSITORY}_eks:${IMAGE_TAG:-latest}
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
    command: "python manage.py migrate"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  worker:
    image: ${REGISTRY}/${REPOSITORY}_eks:${IMAGE_TAG:-latest}
    stdin_open: true
    tty: true
    volumes: [./controlpanel:/home/controlpanel/controlpanel]
    command: ["python", "manage.py", "runworker", "background_tasks"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
