[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
/(
    \.git
    env
    venv
    | migrations
)/
'''

[tool.isort]
profile = 'black'
import_heading_firstparty = 'First-party/Local'
import_heading_future = 'Future'
import_heading_stdlib = 'Standard library'
import_heading_thirdparty = 'Third-party'
line_length = 100
multi_line_output = 3
no_lines_before = 'LOCALFOLDER'
skip_glob = "**/migrations**,venv"
filter_files = true
virtual_env = "venv"
