# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('repository', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
