# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0002_auto_20170816_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='repo_url',
            field=models.URLField(blank=True, default='', max_length=512),
        ),
    ]
