# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0003_auto_20170817_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
