# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0005_auto_20170825_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together=set([('user', 'team')]),
        ),
    ]
