# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0006_auto_20170825_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(message='S3 buckets names must be between 3 and 63 chars', regex='^.{3,63}$'), django.core.validators.RegexValidator(message='Invalid S3 bucket name, check AWS S3 buckets restrictions', regex='^([a-z][a-z0-9-]*[a-z0-9])(.[a-z][a-z0-9-]*[a-z0-9])*$')])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
