# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0007_s3bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3bucket',
            name='name',
            field=models.CharField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='must be between 3 and 63 characters', regex='^.{3,63}$'), django.core.validators.RegexValidator(message='is invalid, check AWS S3 bucket names restrictions (for example, can only contains letters, digits, dots and hyphens)', regex='^([a-z][a-z0-9-]*[a-z0-9])(.[a-z][a-z0-9-]*[a-z0-9])*$')]),
        ),
    ]
