# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0008_auto_20170904_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('access_level', models.CharField(choices=[('readonly', 'Read-only'), ('readwrite', 'Read-write')], default='readonly', max_length=9)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel_api.App')),
                ('s3bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel_api.S3Bucket')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='appdag',
            unique_together=set([('app', 's3bucket')]),
        ),
    ]
