# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 15:52
from __future__ import unicode_literals

import control_panel_api.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0010_auto_20170906_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserS3Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('access_level', models.CharField(choices=[('readonly', 'Read-only'), ('readwrite', 'Read-write')], default='readonly', max_length=9)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='apps3bucket',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps3buckets', to='control_panel_api.App'),
        ),
        migrations.AlterField(
            model_name='apps3bucket',
            name='s3bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps3buckets', to='control_panel_api.S3Bucket'),
        ),
        migrations.AlterField(
            model_name='s3bucket',
            name='name',
            field=models.CharField(max_length=63, unique=True, validators=[control_panel_api.validators.validate_env_prefix, django.core.validators.RegexValidator(message='must be between 3 and 63 characters', regex='^.{3,63}$'), django.core.validators.RegexValidator(message='is invalid, check AWS S3 bucket names restrictions (for example, can only contains letters, digits, dots and hyphens)', regex='^([a-z][a-z0-9-]*[a-z0-9])(.[a-z][a-z0-9-]*[a-z0-9])*$')]),
        ),
        migrations.AddField(
            model_name='users3bucket',
            name='s3bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users3buckets', to='control_panel_api.S3Bucket'),
        ),
        migrations.AddField(
            model_name='users3bucket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users3buckets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='users3bucket',
            unique_together=set([('user', 's3bucket')]),
        ),
    ]
