# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 10:29
from __future__ import unicode_literals

import control_panel_api.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0011_auto_20170927_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s3bucket',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
