# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0011_auto_20170928_1552'),
        ('control_panel_api', '0012_auto_20170928_1029'),
    ]

    operations = [
    ]
