# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0013_merge_20171002_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apps3bucket',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='users3bucket',
            options={'ordering': ('id',)},
        ),
    ]
