# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0015_auto_20171006_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='appuser',
            unique_together=set([('app', 'user')]),
        ),
    ]
