# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0016_auto_20171009_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapp',
            options={'ordering': ('id',)},
        ),
    ]
