# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0017_auto_20171009_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='users',
        ),
        migrations.AlterField(
            model_name='userapp',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userapps', to='control_panel_api.App'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userapps', to=settings.AUTH_USER_MODEL),
        ),
    ]
