# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel_api', '0018_auto_20171012_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='repo_url',
            field=models.URLField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='_repo_name'),
        ),
    ]
