# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_email_verified'),
    ]

    replaces = [('control_panel_api', '0004_s3bucket_is_data_warehouse')]

    operations = [
        migrations.AddField(
            model_name='s3bucket',
            name='is_data_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]