# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_s3bucket_is_data_warehouse'),
    ]

    replaces = [('control_panel_api', '0005_s3bucket_url')]

    operations = [
        migrations.AddField(
            model_name='s3bucket',
            name='location_url',
            field=models.CharField(max_length=128, null=True),
        ),
    ]