# Generated by Django 2.2.3 on 2019-07-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='role',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teams',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
    ]