# Generated by Django 2.2.4 on 2019-08-23 10:01

# Third-party
import django.contrib.postgres.fields.jsonb
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_unused_role_team_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("chart_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "values",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                ("version", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "control_panel_api_tool",
                "ordering": ("name",),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]