# Generated by Django 3.0.5 on 2020-10-19 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_managed_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='target_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]