# Generated by Django 3.1.13 on 2021-10-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201019_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iammanagedpolicy',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='tool',
            name='url_override',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
