# Generated by Django 3.1.6 on 2021-08-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201019_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iammanagedpolicy',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='user',
            name='migration_state',
            field=models.CharField(choices=[('v', 'Void - not involved in migration.'), ('p', 'Pending - the user is able to migrate.'), ('m', 'Migrating - migration has started.'), ('c', 'Complete - migration has completed.'), ('r', 'Reverted - user back on the old platform.')], default='v', help_text="The state of the user's migration to new infrastructure.", max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
