# Generated by Django 3.1.6 on 2021-08-27 12:40

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auto_20210820_1058"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="target_infrastructure",
            field=models.CharField(
                choices=[
                    ("o", "Old pre-EKS infrastructure."),
                    ("e", "Amazon EKS infrastructure."),
                ],
                default="o",
                help_text="The infrastructure this tool targets.",
                max_length=1,
            ),
        ),
    ]
