# Generated by Django 3.1.13 on 2021-10-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211001_1318'),
        ('api', '0015_auto_20210831_1327'),
    ]

    operations = [
    ]
