# Generated by Django 3.2.15 on 2022-09-01 09:03

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_tool_tool_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="apps3bucket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="iammanagedpolicy",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="policys3bucket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="s3bucket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="target_infrastructure",
            field=models.CharField(
                choices=[
                    ("o", "Old pre-EKS infrastructure."),
                    ("e", "Amazon EKS infrastructure."),
                ],
                default="e",
                help_text="The infrastructure this tool targets.",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="migration_state",
            field=models.CharField(
                choices=[
                    ("v", "Void"),
                    ("p", "Pending"),
                    ("m", "Migrating"),
                    ("c", "Complete"),
                    ("r", "Reverted"),
                ],
                default="v",
                help_text="The state of the user's migration to new infrastructure.",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="userapp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="users3bucket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
