# Generated by Django 3.2.15 on 2022-09-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_id_type_and_tool_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAllowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('allowed_ip_ranges', models.TextField()),
            ],
        ),
    ]
