# Generated by Django 3.2.15 on 2022-09-13 16:17

import controlpanel.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_historicalipallowlist_ipallowlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalipallowlist',
            name='allowed_ip_ranges',
            field=models.TextField(validators=[controlpanel.api.validators.validate_ip_ranges]),
        ),
        migrations.AlterField(
            model_name='historicalipallowlist',
            name='contact',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalipallowlist',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalipallowlist',
            name='name',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='ipallowlist',
            name='allowed_ip_ranges',
            field=models.TextField(validators=[controlpanel.api.validators.validate_ip_ranges]),
        ),
        migrations.AlterField(
            model_name='ipallowlist',
            name='contact',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='ipallowlist',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='ipallowlist',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]