# Generated by Django 3.2.15 on 2022-11-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ip_allowlist_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ip_allowlists',
            field=models.ManyToManyField(blank=True, related_name='apps', related_query_name='app', to='api.IPAllowlist'),
        ),
    ]
