# Generated by Django 3.2.15 on 2022-09-27 16:35

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ip_allowlist_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIPAllowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='api.app')),
                ('ip_allowlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_allowlists', to='api.ipallowlist')),
            ],
            options={
                'db_table': 'control_panel_api_app_ip_allowlist',
                'ordering': ('id',),
                'unique_together': {('app', 'ip_allowlist')},
            },
        ),
    ]
