# Generated by Django 4.1.4 on 2022-12-26 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ip_allowlist_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='res_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='apps3bucket',
            name='s3bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.s3bucket'),
        ),
        migrations.AlterField(
            model_name='policys3bucket',
            name='s3bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.s3bucket'),
        ),
        migrations.AlterField(
            model_name='users3bucket',
            name='s3bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.s3bucket'),
        ),
    ]
