# Generated by Django 4.1.4 on 2022-12-26 12:52
import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    AppModel = apps.get_model('api', 'App')
    for row in AppModel.objects.all():
        row.res_id = uuid.uuid4()
        row.save(update_fields=['res_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_app_res_id_alter_apps3bucket_s3bucket_and_more'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
