# Generated by Django 3.2.15 on 2022-12-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_app_ip_allowlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalipallowlist',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipallowlist',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
