# Generated by Django 4.1.4 on 2023-01-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_historicalipallowlist_ipallowlist_isrecommended'),
        ('api', '0023_remove_app_res_id_null'),
    ]

    operations = [
    ]
