# Generated by Django 4.1.4 on 2023-02-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_merge_20230113_2246"),
    ]

    operations = [
        migrations.RunSQL(
            "delete from control_panel_api_app_ip_allowlists;"
        ),
        migrations.RemoveField(
            model_name="app",
            name="ip_allowlists",
        ),
        migrations.AddField(
            model_name="historicalipallowlist",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ipallowlist",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
