# Generated by Django 4.1.4 on 2023-02-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_remove_app_ip_allowlists_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppIPAllowList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deployment_env", models.CharField(max_length=100)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appipallowlists",
                        to="api.app",
                    ),
                ),
                (
                    "ip_allowlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appipallowlists",
                        to="api.ipallowlist",
                    ),
                ),
            ],
            options={
                "db_table": "control_panel_api_app_ip_allowlists",
            },
        ),
        migrations.AddField(
            model_name="app",
            name="ip_allowlists",
            field=models.ManyToManyField(
                blank=True,
                related_name="apps",
                related_query_name="app",
                through="api.AppIPAllowList",
                to="api.ipallowlist",
            ),
        ),
    ]
