# Generated by Django 4.1.4 on 2023-04-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_appipallowlist_app_ip_allowlists"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="app_conf",
            field=models.JSONField(null=True),
        ),
    ]
