# Generated by Django 4.1.4 on 2023-03-15 16:34

import controlpanel.api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_appipallowlist_app_ip_allowlists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s3bucket",
            name="name",
            field=models.CharField(
                max_length=63,
                validators=[
                    controlpanel.api.validators.validate_env_prefix,
                    django.core.validators.RegexValidator(
                        message="must be between 3 and 63 characters", regex="^.{3,63}$"
                    ),
                    django.core.validators.RegexValidator(
                        message="is invalid, check AWS S3 bucket names restrictions (for example, can only contains letters, digits, dots and hyphens)",
                        regex="^([a-z][a-z0-9-]*[a-z0-9])(.[a-z][a-z0-9-]*[a-z0-9])*$",
                    ),
                ],
            ),
        ),
    ]
