# Generated by Django 4.2.1 on 2023-07-30 14:52

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_remove_tool_target_infrastructure"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("entity_class", models.CharField(max_length=20)),
                ("entity_description", models.CharField(max_length=128)),
                ("entity_id", models.BigIntegerField()),
                ("user_id", models.CharField(max_length=128)),
                ("task_id", models.UUIDField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=60)),
                ("task_description", models.CharField(max_length=128)),
                ("queue_name", models.CharField(max_length=60)),
                ("completed", models.BooleanField(default=False)),
                ("message_body", models.CharField(max_length=4000)),
            ],
            options={
                "db_table": "control_panel_api_task",
                "ordering": ("entity_class", "entity_id"),
            },
        ),
    ]
