# Generated by Django 4.2.7 on 2024-02-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_add_soft_delete_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="namespace",
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
