# Generated by Django 4.2.7 on 2024-02-20 16:01

from django.db import migrations


def add_namespaces(apps, schema_editor):
    App = apps.get_model("api", "App")
    for app in App.objects.all():
        app.namespace = f"data-platform-app-{app.slug}"
        app.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_app_namespace"),
    ]

    operations = [
        migrations.RunPython(code=add_namespaces, reverse_code=migrations.RunPython.noop)
    ]
