# Generated by Django 4.2.7 on 2024-02-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_add_namespaces_values_to_apps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="namespace",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
