# Generated by Django 4.2.7 on 2024-03-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_remove_null_blank_from_namespace"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_bedrock_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
