# Generated by Django 4.2.7 on 2024-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_user_is_bedrock_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="justice_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
