# Generated by Django 5.0.4 on 2024-05-31 09:47

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_user_azure_oid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_database_admin",
            field=models.BooleanField(default=False),
        ),
    ]
