# Generated by Django 5.0.4 on 2024-06-13 13:38

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_user_is_database_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="enable_bedrock_access",
            field=models.BooleanField(default=False),
        ),
    ]
