# Generated by Django 5.0.4 on 2024-10-02 08:17

# Third-party
import django.core.validators
from django.db import migrations, models

# First-party/Local
import controlpanel.api.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_app_is_bedrock_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s3bucket",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    controlpanel.api.validators.validate_env_prefix,
                    django.core.validators.RegexValidator(
                        message="is invalid, check AWS S3 bucket names restrictions (for example, can only contains letters, digits, dots and hyphens)",
                        regex="^([a-z][a-z0-9-]*[a-z0-9])(\\.[a-z][a-z0-9-]*[a-z0-9])*\\Z",
                    ),
                    django.core.validators.MinLengthValidator(limit_value=3),
                ],
            ),
        ),
    ]
