# Generated by Django 5.0.4 on 2024-10-04 10:59

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_s3bucket_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="app_type",
            field=models.CharField(
                choices=[("airflow", "Airflow")], default="airflow", max_length=8
            ),
        ),
    ]
