# Generated by Django 5.0.4 on 2024-10-09 15:09

# Third-party
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_alter_parameter_app_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("-created",)},
        ),
    ]
