# Generated by Django 5.0.4 on 2024-10-09 15:58

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_alter_task_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
