# Generated by Django 5.0.4 on 2024-10-10 10:27

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_task_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="retried_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
