# Generated by Django 5.1.2 on 2024-11-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_task_retried_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="is_deprecated",
            field=models.BooleanField(default=False),
        ),
    ]
