# Generated by Django 5.1.2 on 2024-11-19 13:22

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_task_retried_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="cloud_platform_role_arn",
            field=models.CharField(
                default=None,
                help_text="The cloud platform arn for the app",
                max_length=130,
                null=True,
            ),
        ),
    ]
