# Generated by Django 5.1.2 on 2024-11-26 11:26

# Third-party
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_task_retried_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("username",),
                "permissions": [("quicksight_embed_access", "Can access the embedded Quicksight")],
            },
        ),
    ]
