# Generated by Django 5.1.2 on 2024-12-03 10:35

# Third-party
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_app_cloud_platform_role_arn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "satisfaction_rating",
                    models.IntegerField(
                        choices=[
                            (5, "Very satisfied"),
                            (4, "Satisfied"),
                            (3, "Neither satisfied or dissatisfied"),
                            (2, "Dissatisfied"),
                            (1, "Very dissatisfied"),
                        ]
                    ),
                ),
                ("suggestions", models.TextField()),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "control_panel_api_feedback",
            },
        ),
    ]
