# Generated by Django 5.1.2 on 2024-11-29 16:25

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_app_cloud_platform_role_arn"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="is_deprecated",
            field=models.BooleanField(default=False),
        ),
    ]
