# Generated by Django 5.1.2 on 2024-12-03 17:12

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_tool_is_deprecated"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="deprecated_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tool",
            name="is_retired",
            field=models.BooleanField(default=False),
        ),
    ]
