# Generated by Django 5.1.2 on 2024-12-10 15:29

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="suggestions",
            field=models.TextField(blank=True),
        ),
    ]
