# Generated by Django 5.1.2 on 2024-12-09 15:07

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_tool_deprecated_message_tool_is_retired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="deprecated_message",
            field=models.TextField(
                blank=True, help_text="If no message is provided, a default message will be used."
            ),
        ),
    ]
