# Generated by Django 5.1.2 on 2024-11-29 16:25

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_alter_feedback_suggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="is_deprecated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tool",
            name="deprecated_message",
            field=models.TextField(blank=True, help_text="If no message is provided, a default message will be used."),
        ),
        migrations.AddField(
            model_name="tool",
            name="is_retired",
            field=models.BooleanField(default=False),
        ),
    ]
