# Generated by Django 5.1.2 on 2024-12-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_tool_is_deprecated"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="image_tag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
