# Generated by Django 5.1.2 on 2024-12-10 09:01

from django.db import migrations


def add_image_tag(apps, schema_editor):
    Tool = apps.get_model("api", "Tool")
    for tool in Tool.objects.all():
        chart_image_key_name = tool.chart_name.split("-")[0]
        values = tool.values or {}
        image_tag = values.get("{}.tag".format(chart_image_key_name)) or values.get(
            "{}.image.tag".format(chart_image_key_name)
        )
        tool.image_tag = image_tag
        tool.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_tool_image_tag"),
    ]

    operations = [
        migrations.RunPython(code=add_image_tag, reverse_code=migrations.RunPython.noop),
    ]
