# Generated by Django 5.1.2 on 2024-12-27 11:28

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_alter_tool_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("jupyter", "Jupyter"),
                            ("rstudio", "RStudio"),
                            ("vscode", "VSCode"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.tool"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tool",
            name="users_deployed",
            field=models.ManyToManyField(
                related_name="deployed_tools",
                through="api.ToolDeployment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
