# Generated by Django 5.1.2 on 2024-12-27 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_tooldeployment_tool_users_deployed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tooldeployment",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="tooldeployment",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tooldeployment",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tool_deployments",
                to="api.tool",
            ),
        ),
        migrations.AlterField(
            model_name="tooldeployment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tool_deployments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
