# Generated by Django 5.1.2 on 2025-01-20 15:59

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("jupyter", "JupyterLab"),
                            ("rstudio", "RStudio"),
                            ("vscode", "Visual Studio Code"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_deployments",
                        to="api.tool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_deployments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="tool",
            name="users_deployed",
            field=models.ManyToManyField(
                related_name="deployed_tools",
                through="api.ToolDeployment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
