# Generated by Django 5.1.4 on 2025-03-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_tooldeployment_tool_users_deployed"),
    ]

    operations = [
        migrations.CreateModel(
            name="JusticeDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
