# Generated by Django 5.1.4 on 2025-05-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_dashboarddomain_dashboardviewer_dashboard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("username",),
                "permissions": [
                    (
                        "quicksight_embed_author_access",
                        "Can access embedded QuickSight as an author",
                    ),
                    (
                        "quicksight_embed_reader_access",
                        "Can access embedded QuickSight as a reader",
                    ),
                ],
            },
        ),
    ]
