# Generated by Django 5.1.4 on 2025-05-12 11:45

from django.db import migrations


def code(apps, schema_editor):
    """
    This migration is a no-op. It is used to consolidate null values in the
    cloud_platform_role_arn field of the User model.
    """
    App = apps.get_model("api", "App")
    App.objects.filter(cloud_platform_role_arn__isnull=True).update(cloud_platform_role_arn="")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_dashboarddomain_dashboardviewer_dashboard"),
    ]

    operations = [
        migrations.RunPython(code=code, reverse_code=migrations.RunPython.noop),
    ]
