# Generated by Django 5.1.4 on 2025-05-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_cloud_platform_role_arn_consolidate_null_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="cloud_platform_role_arn",
            field=models.CharField(
                blank=True, help_text="The cloud platform arn for the app", max_length=130
            ),
        ),
    ]
