# Generated by Django 5.1.9 on 2025-06-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_alter_app_cloud_platform_role_arn"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tool",
            unique_together={("version", "image_tag", "chart_name", "description", "values")},
        ),
    ]
