# Generated by Django 5.1.10 on 2025-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_statuspageevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuspageevent",
            name="severity",
            field=models.CharField(
                choices=[
                    ("minor", "Minor"),
                    ("major", "Major"),
                    ("all good", "All good"),
                    ("maintenance", "Maintenance"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="statuspageevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("investigating", "Investigating"),
                    ("detected", "Detected"),
                    ("resolved", "Resolved"),
                    ("scheduled", "Scheduled"),
                    ("in progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                max_length=20,
            ),
        ),
    ]
