# Generated by Django 5.2.4 on 2025-09-29 15:53

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_alter_statuspageevent_severity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudPlatformRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "arn",
                    models.CharField(
                        help_text="The cloud platform ARN for the app", max_length=130
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Optional description for this ARN", max_length=255
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_platform_roles",
                        to="api.app",
                    ),
                ),
            ],
            options={
                "db_table": "control_panel_api_cloudplatformrole",
                "unique_together": {("app", "arn")},
            },
        ),
    ]
