# Generated by Django 5.2.4 on 2025-10-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_auto_20250929_1553"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="cloud_platform_role_arn",
        ),
        migrations.AlterField(
            model_name="cloudplatformrole",
            name="arn",
            field=models.CharField(
                db_index=True, help_text="The cloud platform ARN for the app", max_length=130
            ),
        ),
    ]
