# Generated by Django 5.2.8 on 2025-12-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_remove_app_cloud_platform_role_arn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
