# Generated by Django 5.2.10 on 2026-01-23 15:54

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_dashboard_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_admins_added_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.dashboard"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "control_panel_api_dashboard_admins",
            },
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="admins",
            field=models.ManyToManyField(
                related_name="dashboards",
                through="api.DashboardAdmin",
                through_fields=("dashboard", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
