# Generated by Django 5.2.10 on 2026-01-23 15:54

from django.db import migrations


def migrate_admins_to_through_table(apps, schema_editor):
    """
    Copy existing admin relationships to the new through table.
    """
    Dashboard = apps.get_model("api", "Dashboard")
    DashboardAdminAccess = apps.get_model("api", "DashboardAdminAccess")

    for dashboard in Dashboard.objects.all():
        for user in dashboard.admins.all():
            access = DashboardAdminAccess.objects.create(
                dashboard=dashboard,
                user=user,
                added_by=dashboard.created_by,
            )
            # Update created timestamp separately to bypass auto_now_add
            DashboardAdminAccess.objects.filter(pk=access.pk).update(created=dashboard.created)


def reverse_admins_migration(apps, schema_editor):
    """
    Delete data from through table (will be recreated via M2M).
    """
    DashboardAdminAccess = apps.get_model("api", "DashboardAdminAccess")
    DashboardAdminAccess.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_create_dashboard_admin_model"),
    ]

    operations = [
        migrations.RunPython(migrate_admins_to_through_table, reverse_admins_migration),
    ]
