# Generated by Django 5.2.10 on 2026-01-23 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_migrate_dashboard_admin_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="admins",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="admins",
            field=models.ManyToManyField(
                related_name="dashboards",
                through="api.DashboardAdminAccess",
                through_fields=("dashboard", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
