# Generated by Django 5.2.10 on 2026-01-29

from django.db import migrations


def migrate_viewers_to_through_table(apps, schema_editor):
    """
    Copy existing viewer relationships to the new through table.
    """
    Dashboard = apps.get_model("api", "Dashboard")
    DashboardViewerAccess = apps.get_model("api", "DashboardViewerAccess")

    for dashboard in Dashboard.objects.all():
        for viewer in dashboard.viewers.all():
            access = DashboardViewerAccess.objects.create(
                dashboard=dashboard,
                viewer=viewer,
                shared_by=dashboard.created_by,
            )
            # Update created timestamp separately to bypass auto_now_add
            DashboardViewerAccess.objects.filter(pk=access.pk).update(created=dashboard.created)


def reverse_viewers_migration(apps, schema_editor):
    """
    Delete data from through table (will be recreated via M2M).
    """
    DashboardViewerAccess = apps.get_model("api", "DashboardViewerAccess")
    DashboardViewerAccess.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_create_dashboard_viewer_access_model"),
    ]

    operations = [
        migrations.RunPython(migrate_viewers_to_through_table, reverse_viewers_migration),
    ]
