# Generated by Django 5.2.10 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_migrate_dashboard_viewer_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="viewers",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="viewers",
            field=models.ManyToManyField(
                related_name="dashboards",
                through="api.DashboardViewerAccess",
                through_fields=("dashboard", "viewer"),
                to="api.dashboardviewer",
            ),
        ),
    ]
