# Generated by Django 5.2.10 on 2026-01-29

from django.db import migrations


def migrate_domains_to_through_table(apps, schema_editor):
    """
    Copy existing domain relationships to the new through table.
    """
    Dashboard = apps.get_model("api", "Dashboard")
    DashboardDomainAccess = apps.get_model("api", "DashboardDomainAccess")

    for dashboard in Dashboard.objects.all():
        for domain in dashboard.whitelist_domains.all():
            access = DashboardDomainAccess.objects.create(
                dashboard=dashboard,
                domain=domain,
                added_by=dashboard.created_by,
            )
            # Update created timestamp separately to bypass auto_now_add
            DashboardDomainAccess.objects.filter(pk=access.pk).update(created=dashboard.created)


def reverse_domains_migration(apps, schema_editor):
    """
    Delete data from through table (will be recreated via M2M).
    """
    DashboardDomainAccess = apps.get_model("api", "DashboardDomainAccess")
    DashboardDomainAccess.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0076_create_dashboard_domain_access_model"),
    ]

    operations = [
        migrations.RunPython(migrate_domains_to_through_table, reverse_domains_migration),
    ]
