# Generated by Django 5.2.10 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0077_migrate_dashboard_domain_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="whitelist_domains",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="whitelist_domains",
            field=models.ManyToManyField(
                related_name="dashboards",
                through="api.DashboardDomainAccess",
                through_fields=("dashboard", "domain"),
                to="api.dashboarddomain",
            ),
        ),
    ]
