# Generated by Django 5.2.10 on 2026-02-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_switch_dashboard_domains_to_through"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboardadminaccess",
            options={
                "ordering": ["-created"],
                "verbose_name_plural": "dashboard admin access records",
            },
        ),
        migrations.AlterModelOptions(
            name="dashboarddomainaccess",
            options={
                "ordering": ["-created"],
                "verbose_name_plural": "dashboard domain access records",
            },
        ),
        migrations.AlterModelOptions(
            name="dashboardvieweraccess",
            options={
                "ordering": ["-created"],
                "verbose_name_plural": "dashboard viewer access records",
            },
        ),
        migrations.AlterField(
            model_name="dashboardadminaccess",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_access",
                to="api.dashboard",
            ),
        ),
        migrations.AlterField(
            model_name="dashboarddomainaccess",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain_access",
                to="api.dashboard",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardvieweraccess",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewer_access",
                to="api.dashboard",
            ),
        ),
    ]
