# Generated by Django 5.2.11 on 2026-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0080_create_dashboard_historical_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_external_user",
            field=models.BooleanField(default=False),
        ),
    ]
