# Generated by Django 5.2.12 on 2026-03-30 14:13

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0081_user_is_external_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apps3bucket",
            options={
                "ordering": ("id",),
                "verbose_name": "S3 App Access",
                "verbose_name_plural": "S3 App Access records",
            },
        ),
        migrations.AlterModelOptions(
            name="users3bucket",
            options={
                "ordering": ("id",),
                "verbose_name": "S3 User Access",
                "verbose_name_plural": "S3 User Access records",
            },
        ),
        migrations.CreateModel(
            name="HistoricalAppS3Bucket",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("readonly", "Read-only"), ("readwrite", "Read-write")],
                        default="readonly",
                        max_length=9,
                    ),
                ),
                (
                    "paths",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=255,
                            validators=[django.core.validators.RegexValidator("[a-zA-Z0-9_/\\*-]")],
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.app",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "s3bucket",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.s3bucket",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical S3 App Access",
                "verbose_name_plural": "historical S3 App Access records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPolicyS3Bucket",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("readonly", "Read-only"), ("readwrite", "Read-write")],
                        default="readonly",
                        max_length=9,
                    ),
                ),
                (
                    "paths",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=255,
                            validators=[django.core.validators.RegexValidator("[a-zA-Z0-9_/\\*-]")],
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.iammanagedpolicy",
                    ),
                ),
                (
                    "s3bucket",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.s3bucket",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical policy s3 bucket",
                "verbose_name_plural": "historical policy s3 buckets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUserS3Bucket",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("readonly", "Read-only"), ("readwrite", "Read-write")],
                        default="readonly",
                        max_length=9,
                    ),
                ),
                (
                    "paths",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=255,
                            validators=[django.core.validators.RegexValidator("[a-zA-Z0-9_/\\*-]")],
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "s3bucket",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.s3bucket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical S3 User Access",
                "verbose_name_plural": "historical S3 User Access records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
