# Generated by Django 5.2.14 on 2026-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0082_add_historical_s3_access_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="is_comprehend_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
