#!/usr/bin/env python

import argparse
import subprocess


def main():
    args = get_args()
    delete_user(args.username)


def get_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        'username',
        help='Github username')

    return parser.parse_args()


def delete_user(username):
    helm_delete(
        'init-user-{username}'.format(username=username.lower()),
        '--purge'
    )


def helm_delete(release, *flags):
    flags = list(flags)
    subprocess.run(['helm', 'delete', release] + flags, check=True)


if __name__ == '__main__':
    main()
