#!/usr/bin/env python

import argparse
import os
import subprocess


def main():
    args = get_args()
    deploy_rstudio(args.username, args.env, args.tag)


def get_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        'username',
        help='Github username')
    parser.add_argument(
        '--env',
        default=os.environ.get('PLATFORM_ENV', 'dev'),
        help='Name of the platform environment, eg: dev, alpha')
    parser.add_argument(
        '--docker-tag',
        default='latest',
        help='RStudio image tag')

    return parser.parse_args()


def deploy_rstudio(username, env='dev', tag='latest'):
    helm_upgrade(
        '{username}-rstudio'.format(username=username.lower()),
        'charts/rstudio',
        '-f', 'chart-env-config/{env}/rstudio.yml'.format(env=env),
        '--set', 'Username={}'.format(username),
        '--set', 'AWS.IAMRole={env}_user_{username}'.format(
            env=env, username=username),
        '--set', 'RStudio.Image.Tag={}'.format(tag),
        '--namespace', 'user-{username}'.format(username=username)
    )


def helm_upgrade(release, chart, *flags):
    default_flags = ['--install', '--wait']
    flags = list(flags) + default_flags
    subprocess.run(['helm', 'upgrade', release, chart] + flags, check=True)


if __name__ == '__main__':
    main()
