---
options:
    scripts: {}
    client_id: {{client_id}}
    client_secret: {{client_secret}}
    authorizationURL: {{gateway_url}}/auth/oauth/authorize
    tokenURL: {{gateway_url}}/auth/oauth/token
    scope: ''
    customHeaders:
        Authorization: Basic {{ (client_id + ':' + client_secret)|base64enc }}
        Content-Type: application/json
strategy: oauth2
name: {{name}}
is_domain_connection: false
enabled_clients: []
