---
name: 🔖 Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      actions: read
      attestations: write
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install cosign
        id: install_cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1

      - name: Log in to GitHub Container Registry
        id: ghcr_login
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: build_and_push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Sign
        id: sign
        shell: bash
        run: |
          cosign sign --yes "ghcr.io/${{ github.repository }}@${STEPS_BUILD_AND_PUSH_OUTPUTS_DIGEST}"
        env:
          STEPS_BUILD_AND_PUSH_OUTPUTS_DIGEST: ${{ steps.build_and_push.outputs.digest }}

      - name: Generate SBOM
        id: generate_sbom
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          format: cyclonedx-json
          output-file: "sbom.cyclonedx.json"

      - name: Attest
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build_and_push.outputs.digest }}
          push-to-registry: true

      - name: Attest SBOM
        uses: actions/attest-sbom@c604332985a26aa8cf1bdc465b92731239ec6b9e # v4.1.0
        id: attest_sbom
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build_and_push.outputs.digest }}
          sbom-path: sbom.cyclonedx.json
          push-to-registry: true

      - name: cosign Verify
        id: cosign_verify
        shell: bash
        run: |
          cosign verify \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            --certificate-identity="https://github.com/${GITHUB_WORKFLOW_REF}" \
            "ghcr.io/${{ github.repository }}@${STEPS_BUILD_AND_PUSH_OUTPUTS_DIGEST}"
        env:
          STEPS_BUILD_AND_PUSH_OUTPUTS_DIGEST: ${{ steps.build_and_push.outputs.digest }}

      - name: GitHub Attestation Verify
        id: gh_attestation_verify
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh attestation verify "oci://ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME}" --repo ${{ github.repository }}
