---
name: 🩻 Scan

on:
  pull_request:
    branches:
      - main
      - development

permissions: {}

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build
        id: build
        shell: bash
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          make build

      - name: Scan
        id: scan
        run: exit 0 # trivy-action step removed
