---
name: Repo Sync

"on":
  push:
    branches: [main]

jobs:
  repo-sync:
    name: Repo Sync
    if: ${{ github.repository }} == 'analytics-platform-control-panel'
    runs-on: ubuntu-latest
    steps:
      - name: Sync main branch to public fork
        uses: wei/git-sync@v2
        with:
          source_repo: "${{ github.repository }}"
          source_branch: "main"
          destination_repo: "ministryofjustice/analytics-platform-control-panel-public"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
