name: Test

on:
  pull_request:
    branches:
      - main
      - development

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LOGS_BUCKET_NAME: moj-analytics-s3-logs
    permissions:
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build image
        id: build_image
        run: make build
        env:
          NETWORK: host
          IMAGE_TAG: ${{ github.sha }}

      - name: Run Python tests
        id: test
        run: make clean && make test
        env:
          NETWORK: default
          IMAGE_TAG: ${{ github.sha }}
